### PR TITLE
2.6.0: Propose replay attack protection hardfork at 2000000, ref #44

### LINKED ISSUE #30: MEW and Trezor security concern, with EIP 155 implementation
As pointed by https://github.com/kvhnuke/etherwallet/issues/912#issuecomment-323617796  we may need to consider a fast-forward implementation with EIP 155 before UBI. It seems time is quite limited, so another option is to put to v2.x . 

Really appreciate MEW community to point this out.

### LINKED ISSUE #44: Replay attack protection - EIP155, BIP44
<a href="https://github.com/Varunram"></img></a> **Issue by [Varunram](https://github.com/Varunram)**
_Saturday Aug 26, 2017 at 14:00 GMT_
_Originally opened as https://github.com/Musicoin/PM/issues/117_

----

We have to add Replay Attack Prevention (EIP 155) which has been referenced over at the go-musicoin repository. I've added the steps t doing this below.

On the way to adding EIP 155 support there exists<a href="https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki'> this</a> issue with BIP 44 that we must comply with. Once we comply with BIP 44, we can get back on MEW and once we somehow implement EIP 155, we can shut the haters over at the MEW repo.

Let's set a timeline for this before/after UBI,

### LINKED ISSUE #79: Test Byzantium Transition
@immartian @Varunram ref #62 

### GMC v2.6.0 - donotfork branch (for testing)

    git clone https://github.com/5chdn/go-musicoin go-5chdn
    cd ./go-5chdn/
    git checkout a5-fork-donotmerge
    make all
    cd ./build/bin/
    ./gmc --bootnodes "enode://5ddc110733f6d34101973cdef3f9b43484159acf6f816d3b1ee92bc3c98ea453e857bb1207edf0ec0242008ab3a0f9f05eeaee99d47bd414c08a5bdf4847de13@176.9.3.148:30303"

### Parity v1.8.9 or v1.9.2

Chain Spec: [mcip6_byz.json](https://github.com/paritytech/parity/blob/bfeed4ade2ff528b3f595c7389fd8a92b49cea54/ethcore/res/ethereum/mcip6_byz.json)

    wget https://raw.githubusercontent.com/paritytech/parity/bfeed4ade2ff528b3f595c7389fd8a92b49cea54/ethcore/res/ethereum/mcip6_byz.json
    parity --chain mcip6_byz.json

### Result

- Homestead: Block 23
- Byzantium: Block 42

screenshot at 2018-02-08 14-54-45

### PR DESCRIPTION
**Pull request by 5chdn**
Closes #30

Closes #44 

Closes #79

- enables EIP 150 on block 2000000
- enables EIP 155 on block 2000000
- enables EIP 158 on block 2000000
- enables Byzantium on block 2000000

Test instructions in #79

### CODE REVIEW

**Comment by trustfarm-dev** [comment]
EIP 158 will no effect on this fork.
158 is remove spam tx (null) tx , when contract gas ddos Oct 2016.
make slim and decrease chain size.
here musicoin chain no spam tx in main chain, so, it is no-problem, it will on or not.
anyway, no problem.

**Comment by trustfarm-dev** [comment]
And, 1987654 block heights is not a meaning on this time.
Many peer nodes needs to update time and tests, before softforks.
so, 2M (end of feb) is proper choice of block number.
and, many guys easily identifying and remember softfork blocknumber on the view of human.

**Comment by 5chdn** [comment]
Updated block fork number to 2_000_000 and merged #74 

Having EIP-158 is a no-brainer, does not hurt :)

**Comment by trustfarm-dev** [comment]
Go : -)

**Comment by 5chdn** [comment]
Bumps version to 2.6.0 to distinguish the build

**Comment by 5chdn** [comment]
To test:

```
git clone https://github.com/5chdn/go-musicoin go-5chdn
cd ./go-5chdn/
git checkout a5-fork
make all
cd ./build/bin/
./gmc --testnet --bootnodes "enode://a3e94a49488b19c1bcca3dd2dd8e5beb73b64c6528ac736cf259b8625180ca219e6913d6de5188b5a26e05f01a8c540db77a9239f7b6929af1cc451b6003689a@176.9.3.148:30303"
```

Now Parity.

**Pull request merged**
